"""Fixtures: a small self-contained study, built on the fly.

The tests must run on a machine that has only the deposit, and must not depend on the
laboratory archives. Everything here is generated from closed-form dispersions, written to a
temporary directory in the deposit's own input format, and read back through the public
loader -- so the fixtures exercise the file format as well as the physics.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

DEPOSIT = Path(__file__).resolve().parent.parent
STUDIES = DEPOSIT / "studies" / "volet2"


def _write_index(path: Path, wavelengths: np.ndarray, n: np.ndarray, k: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# synthetic dispersion, generated by the test fixtures", "Wavelength_nm,n,k"]
    lines += [f"{w:.4f},{a:.8f},{b:.10f}" for w, a, b in zip(wavelengths, n, k)]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_spectrum(path: Path, wavelengths: np.ndarray, values: np.ndarray, column: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# synthetic spectrum, generated by the test fixtures", f"Wavelength_nm,{column}"]
    # Enough digits that the round trip is limited by the physics, not by the file.
    lines += [f"{w:.6f},{v:.15e}" for w, v in zip(wavelengths, values)]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@pytest.fixture
def synthetic_study_dir(tmp_path: Path) -> Path:
    """A two-sample study whose spectra are generated by the package itself.

    Sample ``plate`` carries stack ``A`` on the front and nothing on the rear; sample
    ``both`` carries ``A`` on the front and ``B`` on the rear. The two share stack ``A``,
    which is what makes the joint inversion non-trivial.
    """
    from certus_re.forward import Evaluator
    from certus_re.io_study import load_study

    wavelengths = np.arange(1000.0, 4001.0, 5.0)
    high = 2.30 - 6.0e-5 * (wavelengths - 1000.0) / 1000.0
    low = 1.46 - 2.0e-5 * (wavelengths - 1000.0) / 1000.0
    substrate = np.full(wavelengths.size, 3.43)
    zero = np.zeros(wavelengths.size)

    _write_index(tmp_path / "indices" / "H.csv", wavelengths, high, zero + 1e-6)
    _write_index(tmp_path / "indices" / "L.csv", wavelengths, low, zero)
    _write_index(tmp_path / "indices" / "sub.csv", wavelengths, substrate, zero)

    document = {
        "name": "synthetic",
        "lambda0_nm": 1500.0,
        "materials": {"H": {"file": "indices/H.csv"}, "L": {"file": "indices/L.csv"}},
        "substrates": {"sub": {"file": "indices/sub.csv"}},
        "stacks": {
            "A": {"run": "A", "layers": [["H", 1.1], ["L", 1.4], ["H", 0.6], ["L", 1.9]]},
            "B": {"run": "B", "layers": [["L", 1.3], ["H", 0.8]]},
        },
        "samples": [
            {
                "name": "plate",
                "substrate": {"material": "sub", "thickness_mm": 1.0, "rear": "bare"},
                "front_stack": "A",
                "measurements": [
                    {
                        "file": "spectra/plate.csv",
                        "column": "R",
                        "units": "fraction",
                        "quantity": "R",
                        "angle_deg": 8.0,
                        "polarization": "a",
                        "sigma": 5e-4,
                    }
                ],
            },
            {
                "name": "both",
                "substrate": {"material": "sub", "thickness_mm": 1.0, "rear": "coated"},
                "front_stack": "A",
                "rear_stack": "B",
                "measurements": [
                    {
                        "file": "spectra/both.csv",
                        "column": "R",
                        "units": "fraction",
                        "quantity": "R",
                        "angle_deg": 45.0,
                        "polarization": "a",
                        "sigma": 5e-4,
                    }
                ],
            },
        ],
        "instrument": {
            "name": "synthetic",
            "beam_aperture_deg": 2.0,
            "aperture_band_edges_nm": [2530.0, 3700.0],
            "aperture_mode": "imposed",
        },
        "free_parameters": {"thicknesses": ["*"], "index_correction": "none"},
    }

    # Placeholder spectra, so that the study can be loaded and then used to generate the
    # real ones from its own forward model.
    _write_spectrum(tmp_path / "spectra" / "plate.csv", wavelengths, np.full(wavelengths.size, 0.3), "R")
    _write_spectrum(tmp_path / "spectra" / "both.csv", wavelengths, np.full(wavelengths.size, 0.3), "R")
    path = tmp_path / "synthetic.json"
    path.write_text(json.dumps(document, indent=2), encoding="utf-8")

    study = load_study(path)
    evaluator = Evaluator(study)
    truth = evaluator.nominal_thicknesses()
    rng = np.random.default_rng(20260911)
    truth = {name: value * (1.0 + rng.normal(0.0, 0.012, value.size)) for name, value in truth.items()}
    predicted = evaluator.predict(truth)
    _write_spectrum(tmp_path / "spectra" / "plate.csv", wavelengths, predicted[0], "R")
    _write_spectrum(tmp_path / "spectra" / "both.csv", wavelengths, predicted[1], "R")

    (tmp_path / "truth.json").write_text(
        json.dumps({name: value.tolist() for name, value in truth.items()}), encoding="utf-8"
    )
    return path


@pytest.fixture
def synthetic_truth(synthetic_study_dir: Path) -> dict[str, np.ndarray]:
    raw = json.loads((synthetic_study_dir.parent / "truth.json").read_text(encoding="utf-8"))
    return {name: np.asarray(value, dtype=float) for name, value in raw.items()}


def deposited(name: str) -> Path:
    path = STUDIES / name
    if not path.is_file():
        pytest.skip(f"deposited study {name} not present")
    return path
