"""Where is the beam aperture, and how well is it known?

The instrument's beam is not collimated, and at 45 degrees that matters: each ray of the cone
sees a different optical thickness, so the fringes of a thick stack wash out. Modelling the
cone as a half-angle about the nominal angle is the only instrument parameter this study uses.

This script determines it the way it should be determined -- by IMPOSING a value and
re-inverting the layer thicknesses at each one. Scanning the nominal design instead would
credit the aperture with everything the thicknesses could have absorbed, and would put the
minimum in the wrong place. The honest scan is the expensive one.

It then reports how well the minimum is located: how far the aperture must move before the
residual rises by one measured photometric repeatability. A minimum that is flat over a whole
degree is not a determination, and saying so is the point of the exercise.

Usage
-----
    python tools/aperture_scan.py
    python tools/aperture_scan.py --study 05_BS17_resolved.json --step 0.05
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

PACKAGE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE))

from certus_re.io_study import load_study  # noqa: E402
from certus_re.solve import invert  # noqa: E402

STUDIES = ("04_BS45_resolved.json", "05_BS17_resolved.json")
SIGMA_REPEAT = 0.00136


def scan(path: Path, values, *, renvert: bool = True):
    rows = []
    for aperture in values:
        study = load_study(path)
        study.instrument.aperture_mode = "imposed"
        study.free.aperture = "imposed"
        study.instrument.aperture_per_band_deg = None
        study.instrument.aperture_band_edges_nm = ()
        study.instrument.beam_aperture_deg = max(float(aperture), 1e-6)
        result = invert(study)
        by_pol = {r.polarization: r for r in result.residuals}
        quad = float(np.sqrt(np.mean([r.rms_final ** 2 for r in result.residuals])))
        before = float(np.sqrt(np.mean([r.rms_initial ** 2 for r in result.residuals])))
        stack = next(iter(result.thicknesses))
        departure = result.qwot_departure_pct()[stack]
        rows.append(
            dict(
                aperture=float(aperture),
                nominal=before,
                fitted=quad,
                per_pol={k: v.rms_final for k, v in by_pol.items()},
                dispersion=float(np.sqrt((departure ** 2).mean())),
                at_bounds=len([b for b in result.at_bounds if "layer" in b]),
                n_layers=len(departure),
                total_nm=float(result.thicknesses[stack].sum()),
            )
        )
    return rows


def report(name: str, rows: list[dict]) -> dict:
    best = min(rows, key=lambda r: r["fitted"])
    print(f"\n=== {name} ===")
    print(f"{'aperture':>9s}{'nominal':>10s}{'inverted':>10s}{'vs best':>10s}"
          f"{'QWOT rms':>10s}{'at bound':>10s}{'total nm':>11s}")
    for r in rows:
        delta = (r["fitted"] - best["fitted"]) / SIGMA_REPEAT
        mark = "  <-- best" if r is best else ""
        print(f"{r['aperture']:9.2f}{100 * r['nominal']:9.3f}%{100 * r['fitted']:9.3f}%"
              f"{delta:+9.2f}s{r['dispersion']:9.2f}%"
              f"{r['at_bounds']:6d}/{r['n_layers']:<3d}{r['total_nm']:11.1f}{mark}")

    # How far can the aperture move before the residual rises by one repeatability?
    inside = [r["aperture"] for r in rows
              if r["fitted"] - best["fitted"] < SIGMA_REPEAT]
    if inside:
        lo, hi = min(inside), max(inside)
        print(f"\n  within one repeatability of the minimum: {lo:.2f} to {hi:.2f} deg"
              f"  (width {hi - lo:.2f} deg)")
        if hi - lo >= 1.0:
            print("  the minimum is FLAT: this component does not determine the aperture")
        else:
            print("  the minimum is located")
    print(f"  best aperture {best['aperture']:.2f} deg, inverted residual "
          f"{100 * best['fitted']:.3f} %, "
          + ", ".join(f"{k} {100 * v:.3f} %" for k, v in sorted(best["per_pol"].items())))
    return best


def write_csv(path: Path, name: str, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(
            "# Beam aperture imposed, layer thicknesses re-inverted at each value.\n"
            f"# Study {name}. Generated by tools/aperture_scan.py.\n"
        )
        writer = csv.writer(handle)
        writer.writerow(
            ["aperture_deg", "rms_nominal_pct", "rms_inverted_pct",
             "qwot_dispersion_pct", "layers_at_bound", "total_nm"]
        )
        for r in rows:
            writer.writerow(
                [f"{r['aperture']:.3f}", f"{100 * r['nominal']:.5f}",
                 f"{100 * r['fitted']:.5f}", f"{r['dispersion']:.4f}",
                 r["at_bounds"], f"{r['total_nm']:.3f}"]
            )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--study", action="append", default=None)
    ap.add_argument("--step", type=float, default=0.25)
    ap.add_argument("--max", type=float, default=3.0)
    ap.add_argument("--out", type=Path, default=PACKAGE / "results")
    args = ap.parse_args()

    print("Beam aperture determined by imposing it and RE-INVERTING the thicknesses at each")
    print("value. Differences are quoted against the measured photometric repeatability,")
    print(f"sigma = {SIGMA_REPEAT}, because a difference smaller than that is not one.")

    values = np.arange(0.0, args.max + 1e-9, args.step)
    for name in (args.study or STUDIES):
        rows = scan(PACKAGE / "studies" / "volet2" / name, values)
        report(name, rows)
        write_csv(args.out / f"aperture_{name[:-5]}.csv", name, rows)
        print(f"  written to results/aperture_{name[:-5]}.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
