"""How much of the answer is the data, and how much is the prior on the thicknesses.

Multilayer reverse engineering is ill-posed. Many thickness vectors reproduce one spectrum to
within the photometry, so the search window declared on each thickness is not a convenience:
it is what selects one of them. This script measures the trade-off instead of asserting it --
it re-inverts a study over a range of windows and reports, for each, the residual it reaches
and the layer-to-layer dispersion of the coating it returns.

The number that makes the result readable is the **measured photometric repeatability**, not
the residual itself. A residual difference smaller than what the instrument repeats to is not
a difference, and on this campaign the whole range from a two-percent window to a fifty-percent
one costs less than half of it -- while the dispersion of the retrieved sixteen-layer coating
varies by a factor of four.

Usage
-----
    python tools/search_window_scan.py [--study 07_joint_campaign] [--out results]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from certus_re.io_study import load_study  # noqa: E402
from certus_re.solve import invert  # noqa: E402

STUDIES = Path(__file__).resolve().parent.parent / "studies" / "volet2"

# The measured repeatability of the photometry, from the repeated acquisition of one specimen
# the campaign contains. Every residual difference below is quoted against it.
SIGMA = 0.00136

WINDOWS = (0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.05, 0.06, 0.08, 0.10, 0.20, 0.50)


def scan(study_path: Path, windows=WINDOWS) -> list[dict]:
    rows: list[dict] = []
    for window in windows:
        study = load_study(study_path)
        result = invert(study, thickness_tolerance=window)
        departures = result.qwot_departure_pct()
        # Over the components only. The witnesses are single layers measured in relative
        # transmittance; their thickness is nowhere near the window, so including them would
        # dilute the very quantity this scan is about.
        components = [r for r in result.residuals if r.quantity == "R"] or result.residuals
        quadratic = float(np.sqrt(np.mean([r.rms_final**2 for r in components])))
        rows.append(
            {
                "window": window,
                "rms_quadratic": quadratic,
                "residuals": {
                    f"{r.sample}_{r.polarization}": r.rms_final for r in result.residuals
                },
                "dispersion": {
                    name: float(np.sqrt((d**2).mean())) for name, d in departures.items()
                },
                "max_departure": {
                    name: float(np.abs(d).max()) for name, d in departures.items()
                },
                "total_departure": {
                    name: float(
                        100.0
                        * (result.qwot[name].sum() - result.nominal_qwot[name].sum())
                        / result.nominal_qwot[name].sum()
                    )
                    for name in departures
                },
                "layers_at_bound": len([b for b in result.at_bounds if "layer" in b]),
            }
        )
        print(
            f"  +/-{100 * window:5.1f} %  rms {100 * quadratic:.3f} %  "
            f"{rows[-1]['layers_at_bound']} at the bound",
            flush=True,
        )
    return rows


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--study", default="07_joint_campaign")
    parser.add_argument(
        "--out", type=Path, default=Path(__file__).resolve().parent.parent / "results"
    )
    args = parser.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    path = STUDIES / f"{args.study}.json"
    if not path.is_file():
        print(f"study not found: {path}", file=sys.stderr)
        return 2

    print(f"scanning the search window on {args.study} ...")
    rows = scan(path)
    best = min(r["rms_quadratic"] for r in rows)
    stacks = sorted(rows[0]["dispersion"])

    measurements = sorted(rows[0]["residuals"])
    header = ["window_pct", "rms_components_pct", "excess_over_best_in_sigma"]
    header += [f"rms_pct_{m}" for m in measurements]
    header += [f"dispersion_pct_{s}" for s in stacks]
    header += [f"max_departure_pct_{s}" for s in stacks]
    header += [f"total_departure_pct_{s}" for s in stacks]
    header += ["layers_at_bound"]

    lines = [
        "# How the retrieved coating depends on the search window declared on the",
        "# thicknesses. Generated by tools/search_window_scan.py.",
        f"# Study: {args.study}. Measured photometric repeatability: {SIGMA:.5f}.",
        "# 'excess_over_best_in_sigma' is how much residual a window costs against the",
        "# loosest one, in units of that repeatability. Below one, it is not a difference.",
        ",".join(header),
    ]
    for r in rows:
        values = [
            f"{100 * r['window']:g}",
            f"{100 * r['rms_quadratic']:.4f}",
            f"{(r['rms_quadratic'] - best) / SIGMA:.3f}",
        ]
        values += [f"{100 * r['residuals'][m]:.4f}" for m in measurements]
        values += [f"{r['dispersion'][s]:.4f}" for s in stacks]
        values += [f"{r['max_departure'][s]:.4f}" for s in stacks]
        values += [f"{r['total_departure'][s]:+.4f}" for s in stacks]
        values += [str(r["layers_at_bound"])]
        lines.append(",".join(values))

    target = args.out / f"search_window_{args.study}.csv"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwritten to {target}")

    declared = load_study(path).free.thickness_tolerance
    chosen = min(rows, key=lambda r: abs(r["window"] - float(declared)))
    print(
        f"\nthe study declares +/-{100 * float(declared):g} %, which costs "
        f"{(chosen['rms_quadratic'] - best) / SIGMA:.2f} times the measured repeatability "
        f"against the loosest window, and returns a layer-to-layer dispersion of "
        + ", ".join(f"{s} {chosen['dispersion'][s]:.2f} %" for s in stacks)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
